### ISSUE TITLE
WKD and importing into roundcube

### ISSUE THREAD

**Issue by mannp** [ddavness/power-mailinabox#11]
Thanks for the new goodies, much appreciated.

I have created a new key pair externally and imported into the key manager.

I've then selected the key in the wkd config against the associated email address.

In roundcube I have tried to search for the keys to add them and they are not found?

SSL etc for the gpg endpoint are all green and reporting no errors.

Should the search work in this way or am I missing something?

Thanks in advance

Edit: Further reading it seems this might be a roundcube issue rather than anything related to power-miab

**Comment by ddavness** [comment]
Probably related to the fact that they didn't implement that yet - it may be related to this:
https://github.com/roundcube/roundcubemail/issues/5999

But it looks like it's not a prioritary feature. As such the only way to get this going is if someone begins a PR to them implementing that feature.

And my PHP is absolutely trash.

**Comment by mannp** [comment]
Yes I'd just ready the same, so realised it was an import a file only thing in roundcube.
