### ISSUE TITLE
EdDSA / ed25519 and Expiry date support

### ISSUE THREAD

**Issue by mannp** [ddavness/power-mailinabox#12]
Thanks for the new additions.

I wondered if in future version you might consider adding ed25519 and expiry date support within the creation of the keys :)

Only thing missing from me using this as my key store and creator.

Edit: It might not be your intention to create the keys yourself, so understand this might be no go...I notice roundcube plugin doesn't have this support either..

**Comment by ddavness** [comment]
The keyring you see in the admin panel and the keyring in the Roundcube webmail are different and _completely isolated_ from eachother.

The keyring I implemented doesn't store private keys (except the daemon key), but as long as the gpg engine supports the algorithm, so does the keyring.

For roundcube, once again, you may want to request that feature to them :)

**Comment by mannp** [comment]
> The keyring I implemented doesn't store private keys (except the daemon key), but as long as the gpg engine supports the algorithm, so does the keyring.

This is what i wasn't aware of, I'd envisaged it would be a general store for pub/priv rather than a pub store only.

I understand how that works now.
