### ISSUE TITLE
How to send as postmaster?

### ISSUE THREAD

**Issue by psychofaktory** [ddavness/power-mailinabox#124]
Hello,

my PMiaB server is incorrectly listed on a DNSBL.

To remove it from the list, the list operator only accepts emails from postmaster@[domain.tld].

But I could not find a way to send an email as postmaster.

How to send an email as postmaster@[domain.tld] with Mail-In-A-Box?

**Comment by ddavness** [comment]
The postmaster alias is automatically configured and linked to `administrator@box.example.com`, which in turn is usually aliased to the first admin account created for the box. You'll need to configure the entity on your own mail client to send as `postmaster` (use the admin account credentials on the SMTP configuration).

To do this on Roundcube Webmail (`https://box.example.com/mail`):
- Login with your admin account (the one `postmaster@` is aliased to);
- Go to **Settings** > **Identities** > **New** and fill in the form (Only the `Email` part is necessary), then click **Save**

![image](https://user-images.githubusercontent.com/45321798/234400307-3c175a95-8bc0-4c07-925f-7dcd398a7064.png)
- When composing messages, click on the "From" field, and you'll see the option to send as `postmaster`:

![image](https://user-images.githubusercontent.com/45321798/234401081-2c78041d-97d9-49c7-85a2-6b360a6f3dc2.png)

**Comment by psychofaktory** [comment]
Tried this, but it didn't work for me.

Here's my scenario:
I have a domain "domain.tld".
My MiaB-Server has the subdomain "mail.domain.tld".
The first user i created is "user@domain.tld".
This user has admin prvilege.
In the alias configuration page in the admin panel "postmaster@mail.domain.tld" is linked to "administrator@mail.domain.tld"
There is also the adress "postmaster@domain.tld" linked to "administrator@mail.domain.tld".
"administrator@mail.domain.tld" in turn is linked to "user@domain.tld".

Then I set up the identidy "postmaster@mail.domain.tld" for "user@domain.tld" in RoundCube webpanel.
I also set up the identidy "postmaster@domain.tld" for "user@domain.tld".

If I try to send from "user@domain.tld" with its alias "postmaster@domain.tld" everything is fine.
But If i try to send from "user@domain.tld" with its alias "postmaster@mail.domain.tld" the following error is show in a popup:
`SMTP Fehler (553): Der Empfänger "mailbox@externaldomain.tld" konnte nicht gesetzt werden (5.7.1 <postmaster@mail.domain.tld>: Sender address rejected: not owned by user user@domain.tld).`

**Comment by psychofaktory** [comment]
Seems that I found the answer myself.

In admin control panel I saw that I set up a Domain Alias for "@domain.tld" linked to "user@domain.tld" before.
Thus I tried to create a Domain Alias for "@mail.domain.tld" linked to "user@domain.tld", too.
After that sending with the identidy "postmaster@mail.domain.tld" from "user@domain.tld" worked for me.
