### ISSUE TITLE
Error updating to v0.54.POWER.1

### ISSUE THREAD

**Issue by mannp** [ddavness/power-mailinabox#19]
Getting the following error updating and wondered if it is exposing my instance? 

Not using B2 back.

```
FAILED: pip2 install --upgrade b2<2.0.0
-----------------------------------------
Collecting b2<2.0.0
  Using cached https://files.pythonhosted.org/packages/03/fd/67295fae98ee32d086e77fc18b477a610bb883c203b799916db060abf31f/b2-1.4.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools
```
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-87ewlJ/b2/

**Comment by ddavness** [comment]
Hi! This was a change I introduced for B2. Try running the following:

```
sudo pip2 install setuptools
```

then rerun the upgrade. Hopefully everything goes right this time :crossed_fingers:

**Comment by mannp** [comment]
Thanks for the prompt and useful reply 👍🏻 worked for me.
