### ISSUE TITLE
Possible to restore a MIAB backup on your version on debian?

### ISSUE THREAD

**Issue by mannp** [ddavness/power-mailinabox#2]
Hi there, its good to see some additional features being added to MIAB, thanks :)

I wondered if it is possible to migrate somehow from MIAB to your power version?

Thanks

**Comment by ddavness** [comment]
Hello there!

Iirc the best approach to migrate from MIAB to this fork is to create a new box (Debian 10 or Ubuntu 20.04, your choice), install PMIAB, and then restore the backup from your old MIAB installation. I _think_ backups from MIAB still work in here.

You can refer to this guide: https://mailinabox.email/maintenance.html#moving-boxes

**Comment by ddavness** [comment]
Speaking about compatibility and stuff like that, you should note that:

MIAB -> PMIAB should work without any hassle (there might be some issues with nginx configurations, though, depending on how you use the web features);

PMIAB -> MIAB should also work on it's core (you get to keep the emails/mailboxes), but you'll lose features (and possibly some secondary features will break)

**Comment by mannp** [comment]
@ddavness thanks for the full answers, appreciated.

Went all in with a new domain and vps install, all working then managed to get locked out of ssh, somehow.

Will be trying a reinstall shortly.

**Comment by ddavness** [comment]
Hi,

Seems that probably you already got around with your installation - I'm going to close this issue. Feel free to follow up if needed.

**Comment by mannp** [comment]
Yes, didn't test the migration but unlikely to do it for a while, so best this is closed.
