### ISSUE TITLE
API Issues adding an alias

### ISSUE THREAD

**Issue by mannp** [ddavness/power-mailinabox#3]
Hi there

I am using the same syntax as MIAB and have triple checked my username and password, but get the error 'Incorrect username or password' when trying to create an alias with the api.

I can do it from the gui, but not the api.....

Does this work for you / others?

Cheers

**Comment by ddavness** [comment]
They work ok for me.

Assuming you're using curl, If the password contains some less conventional characters, it's a good idea to enclose it between quotes - for example let's say your password is `bl4h:bl3h`:

`curl - X VERB ... --user email@domain.tld:"bl4h:bl3h"`

**Comment by mannp** [comment]
Thanks for the clarification.

I had tried the double quotes but it didn't work for me, same error, but I tried this morning with single quotes around everything after --user and the alias was successfully created.
