### ISSUE TITLE
Dark mode option.

### ISSUE THREAD

**Issue by mannp** [ddavness/power-mailinabox#39]
Hi there

I wondered if you had any plans to incorporate the upstream dark mode, or perhaps those changes are incompatible with your front end updates?

Thanks in advance.

**Comment by mannp** [comment]
Fair enough, :) thanks for the clarification.

**Comment by ddavness** [comment]
Work on this will be going on at #41 :)

**Comment by mannp** [comment]
Looking great and super smooth, many thanks.
