### ISSUE TITLE
Roundcube security update

### ISSUE THREAD

**Issue by mannp** [ddavness/power-mailinabox#4]
Hi there

I noticed MIAB getting updated yesterday and wondered if you were following those updates, or wanted us to highlight them here?

https://github.com/mail-in-a-box/mailinabox/issues/1797

Thanks in advance.

**Comment by ddavness** [comment]
Yup, the fixes were imported just now.

[v0.47.POWER.0](https://github.com/ddavness/power-mailinabox/releases/tag/v0.47.POWER.0)
