### ISSUE TITLE
Update Nextcloud version?

### ISSUE THREAD

**Issue by Trevrosa** [ddavness/power-mailinabox#40]
Hi, I'm wondering if updating Nextcloud will be in the future, as Nextcloud version 22.2.3 has a much better performance compared to older versions.

**Comment by ddavness** [comment]
Hi! Because Nextcloud is a bit of a key area for this fork, my "personal" policy for it is following whatever the folks upstream decide. So what will likely happen is that as long as NC 20 remains supported, it will be in use.

**However**, once they do upgrade, I'll promptly follow suit :)

**Comment by Trevrosa** [comment]
Ah okay. Thanks!
