### ISSUE TITLE
Small issue with SMTP Relay

### ISSUE THREAD

**Issue by nitrousnic** [ddavness/power-mailinabox#44]
Hi there,

I have been using Power Mail-in-a-Box for a few weeks now and have been absolutely loving the experience (aside from the small issue I will discuss below).

A few days ago, I decided to start using Sendinblue as an SMTP relay to improve email deliverability. However, I encountered an issue where none of the sent emails from Roundcube was being received by Sendinblue. The status checks show that the SMTP configuration is successful (using STARTTLS).

After looking into the problem, I found the following error message in /var/log/syslog:

Feb 15 22:53:46 srv2 postfix/smtp[39474]: BBFC982148: to=<redacted@gmail.com>, relay=smtp-relay.sendinblue.com[redacted-IP]:587, delay=402, delays=401/0.18/1.4/0, dsn=4.7.0, status=deferred (SASL authentication failed; cannot authenticate to server smtp-relay.sendinblue.com[185.107.232.248]: no mechanism available)

I managed to fix it by running "apt-get install libsasl2-modules" as root. I also checked if it was installed beforehand, and it wasn't. 

Just thought I'd report this small issue (maybe installing libsasl2-modules during setup might be all it takes to fix it?).

Nonetheless, many thanks for your work on Power Mail-in-a-Box. Absolutely love it!

**Comment by nitrousnic** [comment]
No worries! Once again, thank you for your great work on Power Mail-in-a-Box. Good luck with the fix!

**Comment by ddavness** [comment]
I'll keep this issue open until the fix is out, if you don't mind. Just for the record and so that I don't forget 😄

**Comment by nitrousnic** [comment]
Ah sure! Sorry about that! I'm really new to GitHub and am not really familiar with how things are done around here yet 😄

**Comment by ddavness** [comment]
Should be fixed now: https://github.com/ddavness/power-mailinabox/releases/tag/v56.2
