### ISSUE TITLE
Admin panel errors and does not show anything

### ISSUE THREAD

**Issue by jaculate** [ddavness/power-mailinabox#48]
I was updating to the newest version in hopes it fixes my roundcube problems -- this did not happen. Instead, after updating I get this blank admin panel:
![image](https://user-images.githubusercontent.com/98663009/160218855-d7ff77bf-7afe-4a98-9b2c-1929c433128f.png)
with the error:
![image](https://user-images.githubusercontent.com/98663009/160218871-b7d3e9d4-c992-42f2-ad14-3c2532ecc703.png)
(Uncaught TypeError: t.querySelector is not a function
    at new t (focustrap.js:40:5)
    at admin:4877:25)

Any support would be appreciated.
If you would like me to send anything else to help with this issue -- i'd be glad to. Just let me know.

**Comment by jaculate** [comment]
I am also running this on Ubuntu 20.04, That might be why

**Comment by ddavness** [comment]
hi, i reckon that the old bootstrap libraries are cached. youll need to clear it to get the new library.

assuming no errors happened during setup, press shift + f5 while having the admin panel open and it should hopefully fix itself

**Comment by jaculate** [comment]
oh that worked, thank you!
