### ISSUE TITLE
DNSSEC settings not visible on fresh install

### ISSUE THREAD

**Issue by gregwbrooks** [ddavness/power-mailinabox#52]
On a fresh install (Debian 11) the domain entered during installation throws a DNSSEC-needs-to-be-set warning on the status page. This makes sense -- it hasn't been set yet.

However, the message says _"This domain's DNSSEC DS record is not set. The DS record is optional. The DS record activates DNSSEC. See below for instructions."_

No instructions are visible and there are no DNSSEC keys shown ala standard MIAB.

**Comment by gregwbrooks** [comment]
Update: The issue seems to be a button in the HTML that's not rendering on the screen. Viewing the page's HTML shows the missing DNSEC info. The potentially invisible-on-the-screen button HTML:

`<p class="showhide btn btn-light mt-3" href="#">Show More</p>`

**Comment by ddavness** [comment]
Ack'd, I also have a fix ready that I'll be pushing out sometime tomorrow - hang tight!

**Comment by ddavness** [comment]
Fixed in **[v56.5](https://github.com/ddavness/power-mailinabox/releases/tag/v56.5)** :D
