### ISSUE TITLE
Installation stuck at Upgrading NC 19

### ISSUE THREAD

**Issue by cmasterdelphi** [ddavness/power-mailinabox#6]
## Description
Installation stuck/onhold at Upgrading NC19

## Expected Behaviour
- Installation running through AND
- Information about progress

OR

- Error Message

## Actual Behaviour
Nothing (waiting already since 15')
![grafik](https://user-images.githubusercontent.com/56067322/92372246-f0c3a580-f0fc-11ea-8fdf-717d164d4f56.png)

## Additional Info
it seems that it tries to fetch from nextcloud (wget) but its not displayed in install routine
(it worked after 2h of waiting and >300MB download)
![grafik](https://user-images.githubusercontent.com/56067322/92373281-611ef680-f0fe-11ea-9586-00898b683afd.png)

**Comment by ddavness** [comment]
The original project that this repo is forked from has the same behavior as we do, that is not reporting progress. With the low speeds you're reporting (<100KB/s) and the amount of software that we need to download (the NC package alone is 106MB), it's fairly natural that it takes such a long time. (is this your home connection or are you using a cloud provider?) 

In my opinion, it might be better to suggest to the folks over at the main project to report download progress, as more people could benefit from such a change.

**Comment by cmasterdelphi** [comment]
Really, because I rememer that in the original MIAB project, there was something like a progressbar for the wget command showing the overall progress of the download. I know that this is actually an issue with nextcloud not providing enough capacity, but it would increase the user experience for your project to state, why its currently taking so long and that its not an issue with you.

sidenote: i was using a cloud provider (exoscale)

**Comment by ddavness** [comment]
I get your point: if download isnt instantaneous we will have no idea of how long it will take. Ill see what can be done.

> I rememer that in the original MIAB project, there was something like a progressbar for the wget command showing the overall progress of the download.

How long ago was this? After all, if you spin up a new installation of the latest version (0.48 at the moment) of the original Mail-in-a-box project you dont see progress bars either.

**Comment by ddavness** [comment]
The Mail-in-a-Box project updated their NextCloud to version 20, I've imported those changes in here.
