### ISSUE TITLE
Dotted email addresses

### ISSUE THREAD

**Issue by ucsendre** [ddavness/power-mailinabox#63]
Hello,

Is it possible to implement “dots don’t matter” feature in power-mailinabox?
I mean like it works in gmail: https://support.google.com/mail/answer/7436150?hl=en
Too bad MiaB does not support this: https://discourse.mailinabox.email/t/dotted-email-address/9279

Thank you!
Best regards,
Endre

**Comment by leancode** [comment]
You can just create a dotted alias that sends to the non-dotted alias.

**Comment by ddavness** [comment]
As it looks out, the standard says that dots **do** matter. Google even admits that on Google Workspace (aka work or school Google accounts), **johndoe@example.com** and **john.doe@example.com** are two different inboxes and could very well be two different people.

For that reason, I cannot implement such a feature. In fact, it would be a bit awkward if we had someone activate such a feature while having two accounts, **johndoe** and **john.doe** - we could end up in a inconsistent internal state and that would be a giant mess to handle.
