### ISSUE TITLE
Upgrade fails on Nextcloud install step

### ISSUE THREAD

**Issue by leancode** [ddavness/power-mailinabox#67]
I was upgrading from 56.3 (not 100% certain but something of that sort) and got an error. I tried again and screen captured the same error, see below during Nextcloud upgrade step.
The mail server is still running and imap is serving and admin page is up but no nextcloud or webmail.
Where do I go from here?
```
root@ismtp:~# curl -L https://power-mailinabox.net/setup.sh | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2289  100  2289    0     0   8803      0 --:--:-- --:--:-- --:--:--  8803

```
<img width="628" alt="Screenshot 2022-07-20 at 13 21 09" src="https://user-images.githubusercontent.com/611460/179969838-e61e5bc3-c543-427e-869a-004210e2652f.png">
<img width="625" alt="Screenshot 2022-07-20 at 13 22 23" src="https://user-images.githubusercontent.com/611460/179970023-0bfa03fc-ede1-4fbb-9068-850f58bdcba9.png">

```
Primary Hostname: ismtp.redacted.com
Public IP Address: 212.xxx.xxx.xxx
Public IPv6 Address: 2001:xxx:xxxx:xxx::1
Mail-in-a-Box Version:  v56.5

Updating system packages...
Installing system packages...
Initializing system random number generator...
Opening alternate SSH port xxxxx.
Firewall is active and enabled on system startup
Installing nsd (DNS server)...
Installing Postfix (SMTP server)...
Installing Dovecot (IMAP server)...
Installing OpenDKIM/OpenDMARC...
Installing SpamAssassin...
Installing Nginx (web server)...
Installing Roundcube (webmail)...
Installing Nextcloud (contacts/calendar)...
Upgrading Nextcloud --- backing up existing installation, configuration, and database to directory to /home/user-data/owncloud-backup/2022-07-20-13:23:43...

Upgrading to Nextcloud version 21.0.9


FAILED: wget -O /tmp/user_external.tgz https://github.com/nextcloud-releases/user_external/releases/download/v2.1.0/user_external-v2.1.0.tar.gz
-----------------------------------------
--2022-07-20 13:23:56--  https://github.com/nextcloud-releases/user_external/releases/download/v2.1.0/user_external-v2.1.0.tar.gz
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-07-20 13:23:56 ERROR 404: Not Found.

-----------------------------------------
root@ismtp:~#
```

**Comment by leancode** [comment]
OK as I see it there are 2 issues here:
1) The URL for the user_external  is wrong in setup/nextcloud.sh
The script creates:
`https://github.com/nextcloud-releases/user_external/releases/download/v2.1.0/user_external-v2.1.0.tar.gz`
But it should be:
`https://github.com/nextcloud/user_external/releases/download/vv2.1.0/user_external-v2.1.0l.tar.gz`
changing the setup/nextcloud.sh script to reflect this the 21.0.9 upgrade goes well.

From there the plot thickens. The next failure is when installing 22.2.6:
Upgrading to Nextcloud version 22.2.6
FAILED: wget -O /tmp/user_external.tgz https://github.com/nextcloud/user_external/releases/download/v3.0.0/user_external-3.0.0.tar.gz
-----------------------------------------
--2022-07-20 22:10:38--  https://github.com/nextcloud/user_external/releases/download/v3.0.0/user_external-3.0.0.tar.gz
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-07-20 22:10:38 ERROR 404: Not Found.

-----------------------------------------

I will report more when I know more

**Comment by leancode** [comment]
OK the original URL in setup/nextcloud.sh  is correct for the 3.0.0 of user_external but not for the earlier ones.
I would love to do a pull request but I am not that good with bash! Thank you guys. I am back up and running but this is a bug.

**Comment by petertayloruk** [comment]
Any update on this issue? it's borked my install. i've managed to get the webmail to work (which also broke, as i'm guessing the upgrade script stopped halfway through due to incorrect URL for nextcloud install).
But I can't get the admin part of the system to work.

**Comment by leancode** [comment]
@petertayloruk That is exactly what happened to me. While this is open you have to manually edit the url in setup/nextcloud.sh before running the setup script. Also make sure you comment out the pulling of the latest otherwise your edit will be immediately overwriten. This way, version by version I was able to get back up and running.

**Comment by ddavness** [comment]
Yawhoops! I'll take care of that ASAP. Sorry for the delay!

**Comment by ddavness** [comment]
v60.0 was released and the problem should be fixed by now. Otherwise, feel free to reopen!
Thanks for waiting here with me :sweat_smile:
