### ISSUE TITLE
Errors when added a smtp relay.

### ISSUE THREAD

**Issue by jwasia** [ddavness/power-mailinabox#70]
Im using mailgun for the smtp relay creates this error: 'NoneType' object has no attribute 'strip'  , then going into the external dns throws another error: "Something went wrong, sorry". Then adding a new user throws an "Internal Server Error"
  Turning off the smtp relay doesnt keeps the error.. can help fix this? thanks

![shot_220808_212755](https://user-images.githubusercontent.com/73865575/183429511-d3da1ce4-c3a2-4eb4-9716-5c5f6647a745.png)

**Comment by ddavness** [comment]
Alright I figured out what's the issue. It was actually an issue with the DNS. (yay)
The commit above contains a fix for that. The bug should be fixes in the next release.
