### ISSUE TITLE
Roundcube change password

### ISSUE THREAD

**Issue by risturiz** [ddavness/power-mailinabox#77]
Hi, i'm trying to change user passwords from Roundcube without success... This is a bug or a feature?

![roundcubepassword](https://user-images.githubusercontent.com/12375/191302099-f28dc168-f1a2-4324-b7e6-f699819dbe85.png)

I don't see any other option for the user to change their password.

Thanks.

**Comment by risturiz** [comment]
Debian 11 don't have php-mcrypt... Installed with "pecl install mcrypt" and the module is load now:

```
php -m | grep mcrypt
mcrypt
```

But, the error is the same.

**Comment by ddavness** [comment]
Hi! I am able to reproduce - I'll be looking into this.

**Comment by ddavness** [comment]
Done, fix will be released on the next version :)
