### ISSUE TITLE
failed at Upgrading to Nextcloud version 20.0.1 

### ISSUE THREAD

**Issue by infominer33** [ddavness/power-mailinabox#8]
```
FAILED: wget -O /tmp/nextcloud.zip https://download.nextcloud.com/server/releases/nextcloud-20.0.1.zip 
----------------------------------------- 
--2020-12-31 14:27:38--  https://download.nextcloud.com/server/releases/nextcloud-20.0.1.zip 
Resolving download.nextcloud.com (download.nextcloud.com)... failed: Temporary failure in name resolution. 
wget: unable to resolve host address ‘download.nextcloud.com’
```

I'm digging through the setup script now to see what I'm missing...  looks like I've still got a little way to go but will try to hack my way thru it.

**Comment by ddavness** [comment]
Looks like an issue in your end. At the moment the download.nextcloud.com website is up. Did you try to run the setup again? Are you able to download nextcloud from your machine?

**Comment by infominer33** [comment]
I went through the script and manually completed the rest of the steps... turns out I already had the latest version... no clue why it couldn't resolve the first time. Waiting for DNS to clear up but everything appeared to work.
