### ISSUE TITLE
Upgrade instructions on README

### ISSUE THREAD

**Issue by risturiz** [ddavness/power-mailinabox#84]
Btw, the system show the message about upgrade:

"The latest version is v60.1. For upgrade instructions, visit https://power-mailinabox.net" 

But don't have any instructions for newcomers on README, like run again the install command :-)

**Comment by x-FBi** [comment]
curl -L https://power-mailinabox.net/setup.sh | sudo bash
or run from root and remove sudo

I guess your point is "There's no instructions HOW to update"

**Comment by risturiz** [comment]
Yes,  I'm talking about an entry after "Installation" on GitHub readme
